### ISSUE TITLE
library uses pthread.h

### ISSUE THREAD

**Issue by sidey79** [end2endzone/RapidAssist#8]
Sorry, again a problem with cmake

`fatal error C1083: .... "pthread.h": No such file or directory `

I dont think, that i can provide a pthread.h on windows.

**Comment by end2endzone** [comment]
I am confused. pthread.h should not be required on the Windows platform. That is a linux header. See [this](https://github.com/end2endzone/RapidAssist/blob/7be41565ca573f91ac8befb8ca6d71b6b5a8e70d/test/CMakeLists.txt#L37) for reference.

Verify that you properly configured googletest?

**Comment by sidey79** [comment]
That ist what i did with the option:

cmake -DBUILD_GMOCK=0 -DCMAKE_INSTALL_PREFIX=%GTEST_ROOT% -Dgtest_disable_pthreads=on -Dgtest_force_shared_crt=ON ..

I'll look Into that later.

**Comment by end2endzone** [comment]
On my side, I do not have to specify `-Dgtest_disable_pthreads=on`. Also, make sure you do not share the same hard disk space between your Linux and Windows.

I only use `CMAKE_INSTALL_PREFIX` to specify a directory which does not requires administrative privileges and `-Dgtest_force_shared_crt=ON` to have runtime library `Multi-threaded Debug DLL (/MDd)` or `Multi-threaded DLL (/MD)` which is default on Visual Studio.

**Comment by end2endzone** [comment]
I noticed that you call `-DBUILD_GMOCK=0`. Note that CMake boolean option should be specified to `ON` of `OFF`. I do not think that `0` (or `1`) are accepted values. I think that when you call `-DBUILD_GMOCK=0`, this results in an empty solution. See [How to set a CMake option() at command line](https://stackoverflow.com/questions/18435516/how-to-set-a-cmake-option-at-command-line) and [How the heck does one set options](https://cmake.org/pipermail/cmake/2011-November/047168.html) for reference.

**Comment by end2endzone** [comment]
Also note, that if you specify `-DBUILD_GMOCK=OFF`, you **must** also specify `-DBUILD_GTEST=ON` because BUILD_GTEST is set to OFF by default. This is required is you want to only build gtest (and not gmock) according to googletest's CMakeLists.txt:`
```cmake
option(BUILD_GTEST "Builds the googletest subproject" OFF)

#Note that googlemock target already builds googletest
option(BUILD_GMOCK "Builds the googlemock subproject" ON)
```

**Comment by end2endzone** [comment]
On a note more related to the actual issue...

I ran CMake on googletest release-1.8.0 and saw the following at cmake configuration time:
```
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
```

Configuration
git release: release-1.8.0
cmake: version 3.4.3
generator: Visual Studio 10 2010

**Comment by sidey79** [comment]
Whet running 
`
cmake -DBUILD_GMOCK=OFF -DBUILD_GTEST=ON -DCMAKE_INSTALL_PREFIX=%GTEST_ROOT% -Dgtest_force_shared_crt=ON ..
`
at googletest version 1.81  (tried 1.80 also but it's not different)


I have this output also

```
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
```

But on the other side, in CMakeError.log i get this. But may it is not really a fatal error at all.

`build\cmakefiles\cmaketmp\checkincludefile.c(1): fatal error C1083: Datei (Include) ...: "pthread.h": No such file or directory ...build\CMakeFiles\CMakeTmp\cmTC_7da89.vcxproj]`


But after
`cmake --build . --config Release --target install
`
It seems that anything is okay.
```
Der Buildvorgang wurde erfolgreich ausgeführt.
    0 Warnung(en)
    0 Fehler

```

**Comment by sidey79** [comment]
Yust an additonal note overall.

I got it now, compiling a executable of my testproject.  
It's up and running now.  My project is a little bit more complex as just a test of a library.
It checks multiple libraries and how they inteact on my project.


The error C1083 seems not to be so fatal as expected before.

**Comment by end2endzone** [comment]
Your issue seems to be resolved. Are you OK to close the issue?

**Comment by sidey79** [comment]
Yes, we can close. The error comes by checking if pthread is available.
